db:
  image: postgres:9.4
drone:
  build: .
  ports:
    - "8000:8000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - db
  environment:
    - DRONE_DATABASE_DRIVER=postgres
    - DRONE_DATABASE_DATASOURCE="host=db user=postgres dbname=drone sslmode=disable"
